name: Develop CI

on:
  pull_request:
  push:
    branches: [ Develop ]

jobs:
  CI:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    env: 
      ADMIN_FIREBASE_CONFIG_APP_ID: ${{ secrets.ADMIN_FIREBASE_CONFIG_APP_ID }}
      ADMIN_FIREBASE_CONFIG_MEASUREMENT_ID: ${{ secrets.ADMIN_FIREBASE_CONFIG_MEASUREMENT_ID }}
      ADMIN_RESOURCE_ID: ${{ secrets.ADMIN_RESOURCE_ID }}
      ADMIN_URL: ${{ secrets.ADMIN_URL }}
      CONSUMER_FIREBASE_CONFIG_APP_ID: ${{ secrets.CONSUMER_FIREBASE_CONFIG_APP_ID }}
      CONSUMER_FIREBASE_CONFIG_MEASUREMENT_ID: ${{ secrets.CONSUMER_FIREBASE_CONFIG_MEASUREMENT_ID }}
      CONSUMER_URL: ${{ secrets.CONSUMER_URL }}
      CONSUMER_RESOURCE_ID: ${{ secrets.CONSUMER_RESOURCE_ID }}
      FIREBASE_CONFIG_API_KEY: ${{ secrets.FIREBASE_CONFIG_API_KEY }}
      FIREBASE_CONFIG_APP_ID: ${{ secrets.FIREBASE_CONFIG_APP_ID }}
      FIREBASE_CONFIG_AUTH_DOMAIN: ${{ secrets.FIREBASE_CONFIG_AUTH_DOMAIN }}
      FIREBASE_CONFIG_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_CONFIG_MESSAGING_SENDER_ID }}
      FIREBASE_CONFIG_MEASUREMENT_ID: ${{ secrets.FIREBASE_CONFIG_MEASUREMENT_ID }}
      FIREBASE_CONFIG_PROJECT_ID: ${{ secrets.FIREBASE_CONFIG_PROJECT_ID }}
      FIREBASE_CONFIG_STORAGE_BUCKET: ${{ secrets.FIREBASE_CONFIG_STORAGE_BUCKET }}
      FIREBASE_SA_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_SA_PRIVATE_KEY_ID }}
      FIREBASE_SA_PRIVATE_KEY: ${{ secrets.FIREBASE_SA_PRIVATE_KEY }}
      FIREBASE_SA_CLIENT_EMAIL: ${{ secrets.FIREBASE_SA_CLIENT_EMAIL }}
      FIREBASE_SA_CLIENT_ID: ${{ secrets.FIREBASE_SA_CLIENT_ID }}
      FIREBASE_SA_AUTH_URI: ${{ secrets.FIREBASE_SA_AUTH_URI }}
      FIREBASE_SA_TOKEN_URI: ${{ secrets.FIREBASE_SA_TOKEN_URI }}
      FIREBASE_SA_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.FIREBASE_SA_AUTH_PROVIDER_X509_CERT_URL }}
      FIREBASE_SA_CLIENT_X509_CERT_URL: ${{ secrets.FIREBASE_SA_CLIENT_X509_CERT_URL }}
      REST_FIREBASE_CONFIG_APP_ID: ${{ secrets.REST_FIREBASE_CONFIG_APP_ID }}
      REST_FIREBASE_CONFIG_MEASUREMENT_ID: ${{ secrets.REST_FIREBASE_CONFIG_MEASUREMENT_ID }}
      REST_RESOURCE_ID: ${{ secrets.REST_RESOURCE_ID }}
      REST_URL: ${{ secrets.REST_URL }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: |
        sudo npm install --global firebase-tools
        npm ci
    - name: Setup Properties
      run: gulp setup:env
    - name: Install REST
      run: npm ci
      working-directory: ./src/rest
    - name: Run REST Tests
      run: npm run test
      working-directory: ./src/rest
    - name: Install ADMIN
      run: npm ci
      working-directory: ./src/admin
    - name: Run ADMIN Tests
      run: npm run test
      working-directory: ./src/admin
    - name: Install CONSUMER
      run: npm ci
      working-directory: ./src/consumer
    - name: Run CONSUMER Tests
      run: npm run test
      working-directory: ./src/consumer
    

